[
    [
        "mainmenu",
        "20342",
        "widgetEnable.2",
        "yes"
    ],
    [
        "mainmenu",
        "20342",
        "widget.2",
        "Embuary"
    ],
    [
        "mainmenu",
        "20342",
        "widgetName.2",
        "$ADDON[script.embuary.helper 32014]"
    ],
    [
        "mainmenu",
        "20342",
        "widgetType.2",
        ""
    ],
    [
        "mainmenu",
        "20342",
        "widgetTarget.2",
        "videos"
    ],
    [
        "mainmenu",
        "20342",
        "widgetPath.2",
        "plugin://script.embuary.helper/?info=getsimilar&type=movie&pos=0&reload=$INFO[Window(Home).Property(EmbuaryWidgetUpdate)]"
    ],
    [
        "mainmenu",
        "20342",
        "icon",
        "special://skin/extras/icons/film.png"
    ],
    [
        "mainmenu",
        "tvshows",
        "widget",
        "RandomTvShows"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetName",
        "31056"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetType",
        ""
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetPath",
        "special://skin/extras/playlists/RandomTvShows.xsp"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetEnable.2",
        "yes"
    ],
    [
        "mainmenu",
        "tvshows",
        "widget.2",
        "NewTvShows"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetName.2",
        "31053"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetType.2",
        ""
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetTarget.2",
        "videos"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetPath.2",
        "special://skin/extras/playlists/NewShows.xsp"
    ],
    [
        "mainmenu",
        "tvshows",
        "icon",
        "special://skin/extras/icons/tv.png"
    ],
    [
        "mainmenu",
        "744",
        "translatedPath",
        "ActivateWindow(Videos,sources://video/,return)"
    ],
    [
        "mainmenu",
        "744",
        "widget",
        "RecentMovies"
    ],
    [
        "mainmenu",
        "744",
        "widgetName",
        "31046"
    ],
    [
        "mainmenu",
        "744",
        "widgetType",
        ""
    ],
    [
        "mainmenu",
        "744",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "744",
        "widgetPath",
        "special://skin/extras/playlists/RecentMovies.xsp"
    ],
    [
        "mainmenu",
        "744",
        "widgetFullscreen",
        "yes"
    ],
    [
        "mainmenu",
        "744",
        "icon",
        "special://skin/extras/icons/files.png"
    ],
    [
        "mainmenu",
        "music",
        "icon",
        "special://skin/extras/icons/songs.png"
    ],
    [
        "mainmenu",
        "31103",
        "icon",
        "special://skin/extras/icons/livetv.png"
    ],
    [
        "mainmenu",
        "1",
        "icon",
        "special://skin/extras/icons/pictures.png"
    ],
    [
        "mainmenu",
        "0",
        "icon",
        "special://skin/extras/icons/addons.png"
    ],
    [
        "mainmenu",
        "settings",
        "widget",
        "systeminfo"
    ],
    [
        "mainmenu",
        "settings",
        "widgetName",
        "130"
    ],
    [
        "mainmenu",
        "settings",
        "widgetType",
        "system"
    ],
    [
        "mainmenu",
        "settings",
        "widgetTarget",
        "system"
    ],
    [
        "mainmenu",
        "settings",
        "widgetPath",
        "$INCLUDE[skinshortcuts-template-SystemInfoContent]"
    ],
    [
        "mainmenu",
        "settings",
        "icon",
        "special://skin/extras/icons/settings.png"
    ],
    [
        "mainmenu",
        "33060",
        "icon",
        "special://skin/extras/icons/power.png"
    ]
]